//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    
    public enum DataSourceEnum : int
    {
        VK = 0,
        Pikabu = 1,
        Mainfun = 2,
        Joyreactor = 3
    }
}
