//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSources
    {
        public DataSources()
        {
            this.News = new HashSet<News>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Uri { get; set; }
        public DataSourceEnum Type { get; set; }
        public bool IsActive { get; set; }
        public string XMLGuide { get; set; }
        public string BaseUri { get; set; }
        public bool IsNewsSource { get; set; }
    
        public virtual ICollection<News> News { get; set; }
    }
}
