//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    
    public enum DataSourceEnum : int
    {
        VK = 2,
        Pikabu = 3,
        Mainfun = 4,
        Joyreactor = 5,
        OnlineRadio = 1,
        System = 0
    }
}
