//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    
    public enum LogTypeEnum : byte
    {
        BAL = 0,
        DAL = 1,
        WEB = 2,
        CORE = 3,
        FE = 4
    }
}
