//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Comments = new HashSet<Comments>();
            this.UsersImage = new HashSet<UsersImage>();
        }
    
        public int Id { get; set; }
        public string PostId { get; set; }
        public string AuthorName { get; set; }
        public string AuthorId { get; set; }
        public string AuthorLink { get; set; }
        public int PostLikes { get; set; }
        public string PostName { get; set; }
        public string PostLink { get; set; }
        public string PostContent { get; set; }
        public string PostTags { get; set; }
        public bool External { get; set; }
        public bool IsActive { get; set; }
        public bool AdultContent { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public System.DateTime ModificationDateTime { get; set; }
    
        public virtual DataSources DataSource { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<UsersImage> UsersImage { get; set; }
    }
}
