//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RssAggregatorModelContainer : DbContext
    {
        public RssAggregatorModelContainer()
            : base("name=RssAggregatorModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DataSources> DataSourcesSet { get; set; }
        public DbSet<News> NewsSet { get; set; }
        public DbSet<User> UserSet { get; set; }
        public DbSet<Template> TemplateSet { get; set; }
        public DbSet<Comments> CommentsSet { get; set; }
        public DbSet<UsersImage> UsersImageSet { get; set; }
        public DbSet<Icons> IconsSet { get; set; }
        public DbSet<Log> LogSet { get; set; }
        public DbSet<NewDataSourceRequest> NewDataSourceRequestSet { get; set; }
        public DbSet<UserFeedback> UserFeedbackSet { get; set; }
        public DbSet<UserMessages> UserMessagesSet { get; set; }
        public DbSet<Settings> SettingsSet { get; set; }
    }
}
