//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    
    public enum TagTypeEnum : int
    {
        Text = 0,
        Img = 1,
        Link = 2,
        Audio = 3,
        Video = 4
    }
}
