//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.News = new HashSet<News>();
            this.Comments = new HashSet<Comments>();
            this.Image = new HashSet<UsersImage>();
            this.NewDataSourceRequest = new HashSet<NewDataSourceRequest>();
            this.UserFeedback = new HashSet<UserFeedback>();
            this.UserMessagesSend = new HashSet<UserMessages>();
            this.UserMessagesRecived = new HashSet<UserMessages>();
            this.UserActivityLog = new HashSet<UserActivityLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public UserTypeEnum Type { get; set; }
        public bool IsActive { get; set; }
        public string UserKey { get; set; }
        public LocationEnum Location { get; set; }
    
        public virtual ICollection<News> News { get; set; }
        public virtual Template Template { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<UsersImage> Image { get; set; }
        public virtual ICollection<NewDataSourceRequest> NewDataSourceRequest { get; set; }
        public virtual ICollection<UserFeedback> UserFeedback { get; set; }
        public virtual ICollection<UserMessages> UserMessagesSend { get; set; }
        public virtual ICollection<UserMessages> UserMessagesRecived { get; set; }
        public virtual ICollection<UserActivityLog> UserActivityLog { get; set; }
    }
}
