//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog
    {
        public int Id { get; set; }
        public string UserKey { get; set; }
        public bool IsNew { get; set; }
        public ActivityEnum Activity { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Browser { get; set; }
        public int BrowserVersion { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
    
        public virtual User User { get; set; }
    }
}
