//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssAgregator.DAL
{
    using System;
    
    public enum UserTypeEnum : byte
    {
        System = 0,
        Admin = 1,
        Moderator = 2,
        User = 3,
        Anonymous = 4
    }
}
